- id: license-header
  name: Adding license headers
  entry: license-header
  language: python
  types_or: [python]
  description: Add license headers to python files
  minimum_pre_commit_version: 2.9.0
