- id: license-headers
  name: Add license headers
  entry: license-headers
  language: python
  types_or: [python]
  description: Add license headers to python files
  minimum_pre_commit_version: 2.9.0
